name: astropc
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/ilbagatto/astropc

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.5.0
  vector_math: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  
